# Generated by Django 4.0.6 on 2022-08-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url_1',
            field=models.CharField(default='https://protkd.com/wp-content/uploads/2017/04/default-image.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url_2',
            field=models.CharField(default='https://protkd.com/wp-content/uploads/2017/04/default-image.jpg', max_length=500),
        ),
    ]
